/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.edu.ifg.cracha.geral.visao;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author SWITCH
 */
public class VisaoCracha extends javax.swing.JFrame {

    /**
     * Creates new form VisaoCracha
     */
    public VisaoCracha() {
  
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pMainPanel = new javax.swing.JPanel();
        pTitlePanel = new javax.swing.JPanel();
        lTitulo = new javax.swing.JLabel();
        pButtons = new javax.swing.JPanel();
        bSair = new javax.swing.JButton();
        bPrint = new javax.swing.JButton();
        pDataBase = new javax.swing.JPanel();
        lURLDB = new javax.swing.JLabel();
        tfURLDB = new javax.swing.JTextField("eventif");
        lUser = new javax.swing.JLabel();
        tfUser = new javax.swing.JTextField("postgres");
        lPassword = new javax.swing.JLabel();
        pfPassword = new javax.swing.JPasswordField("ifg");
        lSQL = new javax.swing.JLabel();
        scSQL = new javax.swing.JScrollPane();
        taSQL = new javax.swing.JTextArea("select * from participantes");
        bConecta = new javax.swing.JButton();
        pReport = new javax.swing.JPanel();
        lURLReport = new javax.swing.JLabel();
        tfURLReport = new javax.swing.JTextField("-");
        pQR = new javax.swing.JPanel();
        lURLQR = new javax.swing.JLabel();
        tfURLQR = new javax.swing.JTextField("\\QRCodes");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("fVisaoCracha"); // NOI18N
        setUndecorated(true);

        pMainPanel.setBackground(new java.awt.Color(204, 102, 0));
        pMainPanel.setName("pMainPanel"); // NOI18N

        pTitlePanel.setBackground(new java.awt.Color(255, 255, 255));

        lTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lTitulo.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lTitulo.setForeground(new java.awt.Color(204, 102, 0));
        lTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitulo.setText("Gerador de Crachás V SeCiTec");
        lTitulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 3, true));

        javax.swing.GroupLayout pTitlePanelLayout = new javax.swing.GroupLayout(pTitlePanel);
        pTitlePanel.setLayout(pTitlePanelLayout);
        pTitlePanelLayout.setHorizontalGroup(
            pTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pTitlePanelLayout.setVerticalGroup(
            pTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        pButtons.setBackground(new java.awt.Color(255, 255, 255));

        bSair.setBackground(new java.awt.Color(204, 102, 0));
        bSair.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        bSair.setForeground(new java.awt.Color(255, 255, 255));
        bSair.setText("Sair");
        bSair.setMaximumSize(new java.awt.Dimension(30, 30));
        bSair.setMinimumSize(new java.awt.Dimension(30, 30));

        bPrint.setBackground(new java.awt.Color(204, 102, 0));
        bPrint.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        bPrint.setForeground(new java.awt.Color(255, 255, 255));
        bPrint.setText("Gerar Crachás");

        javax.swing.GroupLayout pButtonsLayout = new javax.swing.GroupLayout(pButtons);
        pButtons.setLayout(pButtonsLayout);
        pButtonsLayout.setHorizontalGroup(
            pButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bSair, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pButtonsLayout.setVerticalGroup(
            pButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bPrint, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addContainerGap())
        );

        pDataBase.setBackground(new java.awt.Color(255, 255, 255));
        pDataBase.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Banco de Dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 0, 12), new java.awt.Color(204, 102, 0))); // NOI18N

        lURLDB.setForeground(new java.awt.Color(204, 102, 0));
        lURLDB.setText("jdbc:postgresql://localhost:5432/");

        tfURLDB.setBackground(new java.awt.Color(204, 102, 0));
        tfURLDB.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        tfURLDB.setForeground(new java.awt.Color(255, 255, 255));

        lUser.setForeground(new java.awt.Color(204, 102, 0));
        lUser.setText("Usuário");

        tfUser.setBackground(new java.awt.Color(204, 102, 0));
        tfUser.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        tfUser.setForeground(new java.awt.Color(255, 255, 255));

        lPassword.setForeground(new java.awt.Color(204, 102, 0));
        lPassword.setText("Senha");

        pfPassword.setBackground(new java.awt.Color(204, 102, 0));
        pfPassword.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        pfPassword.setForeground(new java.awt.Color(255, 255, 255));

        lSQL.setForeground(new java.awt.Color(204, 102, 0));
        lSQL.setText("SQL");

        taSQL.setBackground(new java.awt.Color(204, 102, 0));
        taSQL.setColumns(20);
        taSQL.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        taSQL.setForeground(new java.awt.Color(255, 255, 255));
        taSQL.setRows(5);
        scSQL.setViewportView(taSQL);

        bConecta.setBackground(new java.awt.Color(204, 102, 0));
        bConecta.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        bConecta.setForeground(new java.awt.Color(255, 255, 255));
        bConecta.setText("Conectar");

        javax.swing.GroupLayout pDataBaseLayout = new javax.swing.GroupLayout(pDataBase);
        pDataBase.setLayout(pDataBaseLayout);
        pDataBaseLayout.setHorizontalGroup(
            pDataBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDataBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDataBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pDataBaseLayout.createSequentialGroup()
                        .addComponent(lURLDB, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfURLDB, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(pDataBaseLayout.createSequentialGroup()
                        .addGroup(pDataBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lUser)
                            .addComponent(lPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pDataBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfUser, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(pfPassword))
                        .addGap(10, 10, 10)))
                .addComponent(lSQL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pDataBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bConecta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scSQL, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pDataBaseLayout.setVerticalGroup(
            pDataBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDataBaseLayout.createSequentialGroup()
                .addGroup(pDataBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDataBaseLayout.createSequentialGroup()
                        .addGroup(pDataBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lURLDB, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfURLDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lSQL))
                        .addGap(18, 18, 18)
                        .addGroup(pDataBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lUser)
                            .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(scSQL, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pDataBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPassword)
                    .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bConecta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pReport.setBackground(new java.awt.Color(255, 255, 255));
        pReport.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Relatório", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 0, 12), new java.awt.Color(204, 102, 0))); // NOI18N
        pReport.setPreferredSize(new java.awt.Dimension(238, 48));

        lURLReport.setForeground(new java.awt.Color(204, 102, 0));
        lURLReport.setText("URL");

        tfURLReport.setBackground(new java.awt.Color(204, 102, 0));
        tfURLReport.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pReportLayout = new javax.swing.GroupLayout(pReport);
        pReport.setLayout(pReportLayout);
        pReportLayout.setHorizontalGroup(
            pReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pReportLayout.createSequentialGroup()
                .addComponent(lURLReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfURLReport, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addContainerGap())
        );
        pReportLayout.setVerticalGroup(
            pReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lURLReport, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(tfURLReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pQR.setBackground(new java.awt.Color(255, 255, 255));
        pQR.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "QR-Code", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 102, 0))); // NOI18N
        pQR.setPreferredSize(new java.awt.Dimension(238, 47));

        lURLQR.setForeground(new java.awt.Color(204, 102, 0));
        lURLQR.setText("URL");

        tfURLQR.setBackground(new java.awt.Color(204, 102, 0));
        tfURLQR.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pQRLayout = new javax.swing.GroupLayout(pQR);
        pQR.setLayout(pQRLayout);
        pQRLayout.setHorizontalGroup(
            pQRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pQRLayout.createSequentialGroup()
                .addComponent(lURLQR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfURLQR, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
        );
        pQRLayout.setVerticalGroup(
            pQRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pQRLayout.createSequentialGroup()
                .addGroup(pQRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lURLQR, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfURLQR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pMainPanelLayout = new javax.swing.GroupLayout(pMainPanel);
        pMainPanel.setLayout(pMainPanelLayout);
        pMainPanelLayout.setHorizontalGroup(
            pMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMainPanelLayout.createSequentialGroup()
                        .addComponent(pReport, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pQR, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pButtons, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pDataBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pMainPanelLayout.setVerticalGroup(
            pMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pDataBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pQR, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public JButton getbConecta() {return bConecta;}

    public JButton getbPrint() {return bPrint;}

    public JButton getbSair() {return bSair;}

    public JPasswordField getPfPassword() {return pfPassword;}

    public JTextArea getTaSQL() {return taSQL;}

    public JTextField getTfURLDB() {return tfURLDB;}

    public JTextField getTfURLQR() {return tfURLQR;}

    public JTextField getTfURLReport() {return tfURLReport;}

    public JTextField getTfUser() {return tfUser;}

    public JPanel getpMainPanel() {return pMainPanel;}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bConecta;
    private javax.swing.JButton bPrint;
    private javax.swing.JButton bSair;
    private javax.swing.JLabel lPassword;
    private javax.swing.JLabel lSQL;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JLabel lURLDB;
    private javax.swing.JLabel lURLQR;
    private javax.swing.JLabel lURLReport;
    private javax.swing.JLabel lUser;
    private javax.swing.JPanel pButtons;
    private javax.swing.JPanel pDataBase;
    private javax.swing.JPanel pMainPanel;
    private javax.swing.JPanel pQR;
    private javax.swing.JPanel pReport;
    private javax.swing.JPanel pTitlePanel;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JScrollPane scSQL;
    private javax.swing.JTextArea taSQL;
    private javax.swing.JTextField tfURLDB;
    private javax.swing.JTextField tfURLQR;
    private javax.swing.JTextField tfURLReport;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables
}
